apiVersion: v1                 # Core API group
kind: Service                  # Object type = Service

metadata:
  name: nginx-svc              # Service name
  namespace: nginx-ns          # Target namespace

spec:
  selector:
    app: nginx                 # Must match Pod labels

  ports:
  - protocol: TCP
    port: 82                   # Service port (cluster side)
    targetPort: 80             # Container port inside Pod

  type: ClusterIP              # Default service type